name: Question
description: Ask a question about git-parsec
labels: ["type/question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're happy to help!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant context (what you're trying to do, environment, etc.).
    validations:
      required: false
